version: '2'

services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ************
      MYSQL_DATABASE: databasename
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  fpm:
    image: fastwebmedia/php72-fpm-bedrock-wordpress
    container_name: fpm
    links:
      - mariadb:mariadb
    volumes:
      - ./wordpress:/var/www/html
    environment:
      DB_NAME: databasename
      DB_USER: root
      DB_PASSWORD: ************
      DB_HOST: mariadb
      WP_ENV: development
      WP_HOME: http://127.0.0.1
      WP_SITEURL: http://127.0.0.1/wp
  nginx:
    image: fastwebmedia/nginx-bedrock-wordpress
    container_name: nginx
    links:
      - fpm:fpm
    depends_on:
      - fpm
    volumes_from:
      - fpm
    ports:
      - "80:80"
    environment:
      ALLOW_INSTALL: "yes"
  backup:
    image: fastwebmedia/mysql-backup-s3
    links:
      - mariadb:mariadb
    depends_on:
      - mariadb
    environment:
      S3_ACCESS_KEY_ID: ********************
      S3_SECRET_ACCESS_KEY: *****************************
      S3_BUCKET: bucket-name
      S3_PREFIX: db_backup
      S3_S3V4: "yes"
      S3_REGION: eu-west-2
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: **********
      MYSQLDUMP_DATABASE: databasename
      SCHEDULE: '@hourly'
